import { renameSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import type { ToolProposal } from './types.ts';

/** Snake_case names only — defense-in-depth mirroring write.ts's
 *  NAME_PATTERN check: write-tool.ts must not trust that every caller
 *  already ran validate-tool.ts. */
const NAME_PATTERN = /^[a-z][a-z0-9_]*$/;

function atomicWrite(path: string, content: string): void {
  const tmp = `${path}.tmp`;
  writeFileSync(tmp, content);
  renameSync(tmp, path);
}

/** Write a brand-new tool-code PROPOSAL to `proposalsDir/<name>.proposal.ts`
 *  for human review — mirrors write.ts's atomic-write discipline for agents,
 *  minus any registry/index/mcp wiring. That omission is deliberate: unlike
 *  `writeAgent`, this never touches `agents/index.ts` or any tool registry,
 *  so the proposal can never be picked up and activated in the same run.
 *  Activation is a separate, later, human-driven step. */
export function writeToolProposal(
  p: ToolProposal,
  proposalsDir: string,
): string {
  if (!NAME_PATTERN.test(p.name)) {
    throw new Error(
      `writeToolProposal: invalid tool name ${JSON.stringify(p.name)} — must match ${NAME_PATTERN}`,
    );
  }
  const banner = [
    '// PROPOSAL — generated by the agent-builder (Task 24).',
    "// NOT wired into any agent's toolset and not imported anywhere.",
    '// Review this code, then deliberately move/import it to activate it.',
    '',
    '',
  ].join('\n');
  const path = join(proposalsDir, `${p.name}.proposal.ts`);
  atomicWrite(path, banner + p.code);
  return path;
}
