import { readFileSync, renameSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { getPackEntry } from '../mcp/pack.ts';
import type { AgentProposal } from './types.ts';

export type WritePaths = {
  agentsDir: string;
  indexPath: string;
  mcpConfigPath: string;
};

export function pascalCase(snake: string): string {
  return snake
    .split('_')
    .filter(Boolean)
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join('');
}

function atomicWrite(path: string, content: string): void {
  const tmp = `${path}.tmp`;
  writeFileSync(tmp, content);
  renameSync(tmp, path);
}

function renderAgentFile(p: AgentProposal): string {
  const Factory = `create${pascalCase(p.name)}Agent`;
  // JSON.stringify safely escapes the generated strings into TS string literals.
  return `import type { ToolSet } from 'ai';
import qwenFast from '../models/qwen-fast.ts';
import type { Agent } from '../src/core/agent-def.ts';
import { Capability, PreferPolicy } from '../src/core/types.ts';
import { createOllamaModel } from '../src/providers/ollama.ts';

// Generated by the agent-builder (Slice 17). Safe to edit by hand.
const SYSTEM_PROMPT = ${JSON.stringify(p.systemPrompt)};

export function ${Factory}(tools: ToolSet): Agent {
  return {
    name: '${p.name}', // validated snake_case ([a-z][a-z0-9_]*) — safe unescaped
    description: ${JSON.stringify(p.description)},
    model: createOllamaModel(qwenFast),
    systemPrompt: SYSTEM_PROMPT,
    tools,
    modelDecl: qwenFast,
    modelReq: {
      role: ${JSON.stringify(p.modelReq.role)},
      requires: [Capability.Tools],
      prefer: PreferPolicy.LargestThatFits,
    },
  };
}
`;
}

function registerInIndex(indexPath: string, p: AgentProposal): void {
  const Factory = `create${pascalCase(p.name)}Agent`;
  let idx = readFileSync(indexPath, 'utf8');
  const importLine = `import { ${Factory} } from './${p.name}.ts';\n`;
  const entryLine = `  ${p.name}: ${Factory},\n`;
  const IMPORTS = '// AGENT-BUILDER:IMPORTS';
  const ENTRIES = '// AGENT-BUILDER:ENTRIES';
  if (!idx.includes(IMPORTS) || !idx.includes(ENTRIES)) {
    throw new Error(`agents/index.ts is missing the AGENT-BUILDER markers`);
  }
  if (!idx.includes(importLine))
    idx = idx.replace(IMPORTS, importLine + IMPORTS);
  if (!idx.includes(entryLine)) idx = idx.replace(ENTRIES, entryLine + ENTRIES);
  atomicWrite(indexPath, idx);
}

function scopeMcp(mcpConfigPath: string, p: AgentProposal): void {
  let cfg: { mcpServers?: Record<string, Record<string, unknown>> } = {};
  try {
    cfg = JSON.parse(readFileSync(mcpConfigPath, 'utf8'));
  } catch {
    cfg = {};
  }
  if (!cfg.mcpServers) cfg.mcpServers = {};
  const servers = cfg.mcpServers;
  for (const s of p.suggestedServers) {
    const entry = getPackEntry(s.packName);
    if (!entry) continue; // validate.ts already guarantees palette membership
    if (!servers[s.packName]) servers[s.packName] = { ...entry.server };
    const current = servers[s.packName] as Record<string, unknown>;
    const agents = Array.isArray(current.agents)
      ? (current.agents as string[])
      : [];
    if (!agents.includes(p.name)) agents.push(p.name);
    current.agents = agents;
  }
  atomicWrite(mcpConfigPath, `${JSON.stringify(cfg, null, 2)}\n`);
}

/** Write the generated agent file, register it in agents/index.ts, and add/scope
 *  its suggested pack servers in mcp.json. Atomic per file. Returns files written. */
export function writeAgent(p: AgentProposal, paths: WritePaths): string[] {
  const written: string[] = [];
  const agentPath = join(paths.agentsDir, `${p.name}.ts`);
  atomicWrite(agentPath, renderAgentFile(p));
  written.push(agentPath);
  registerInIndex(paths.indexPath, p);
  written.push(paths.indexPath);
  if (p.suggestedServers.length > 0) {
    scopeMcp(paths.mcpConfigPath, p);
    written.push(paths.mcpConfigPath);
  }
  return written;
}
