import { CrewProcess } from '../crew/types.ts';
import type {
  CrewIR,
  InputDescriptor,
  PredicateDescriptor,
  WorkflowIR,
} from './ir.ts';
import type { Shape } from './types.ts';

/** Every string value emitted into generated source goes through this — never
 *  raw interpolation. Deterministic + injection/escaping-safe by construction. */
const j = (v: unknown): string => JSON.stringify(v);

function renderInput(d: InputDescriptor): string {
  if (d.kind === 'fromInput') return 'fromInput()';
  if (d.kind === 'fromStep') return `fromStep(${j(d.ref)})`;
  return `fromTemplate(${j(d.template)})`;
}

function renderPredicate(d: PredicateDescriptor): string {
  if (d.kind === 'whenEquals') return `whenEquals(${j(d.ref)}, ${j(d.value)})`;
  if (d.kind === 'whenContains')
    return `whenContains(${j(d.ref)}, ${j(d.substr)})`;
  return `whenTruthy(${j(d.ref)})`;
}

const KIND: Record<WorkflowIR['steps'][number]['kind'], string> = {
  agent: 'StepKind.Agent',
  tool: 'StepKind.Tool',
  branch: 'StepKind.Branch',
  map: 'StepKind.Map',
};

function renderWorkflowStep(s: WorkflowIR['steps'][number]): string {
  const dep =
    'dependsOn' in s && s.dependsOn
      ? `    dependsOn: ${j(s.dependsOn)},\n`
      : '';
  const head = `  {\n    id: ${j(s.id)},\n    kind: ${KIND[s.kind]},\n${dep}`;

  if (s.kind === 'agent') {
    const verify = s.verify ? '    verify: true,\n' : '';
    return `${head}    agent: ${j(s.agent)},\n    input: ${renderInput(s.input)},\n    output: z.string(),\n${verify}  }`;
  }
  if (s.kind === 'tool') {
    return `${head}    tool: ${j(s.tool)},\n    input: ${renderInput(s.input)},\n    output: z.unknown(),\n  }`;
  }
  if (s.kind === 'branch') {
    return `${head}    predicate: ${renderPredicate(s.predicate)},\n    whenTrue: ${j(s.whenTrue)},\n    whenFalse: ${j(s.whenFalse)},\n    output: z.unknown(),\n  }`;
  }
  // map
  const sub =
    s.step.kind === 'agent'
      ? `{ kind: StepKind.Agent, agent: ${j(s.step.agent)}, input: ${renderInput(s.step.input)}, output: z.string() }`
      : `{ kind: StepKind.Tool, tool: ${j(s.step.tool)}, input: ${renderInput(s.step.input)}, output: z.unknown() }`;
  return `${head}    over: mapOver(${j(s.over.ref)}),\n    step: ${sub},\n    output: z.unknown(),\n  }`;
}

function transpileWorkflow(ir: WorkflowIR): string {
  const steps = ir.steps.map(renderWorkflowStep).join(',\n');
  return `import { z } from 'zod';
import { defineWorkflow } from '../src/workflow/define.ts';
import { StepKind } from '../src/workflow/types.ts';
import { fromInput, fromStep, fromTemplate, mapOver, whenContains, whenEquals, whenTruthy } from '../src/crew-builder/safe-helpers.ts';

// Generated by the crew/workflow-builder (Slice 19). Safe to edit by hand.
export default defineWorkflow({
  id: ${j(ir.id)},${ir.description ? `\n  description: ${j(ir.description)},` : ''}
  steps: [
${steps},
  ],
});
`;
}

function transpileCrew(ir: CrewIR): string {
  const members = ir.members
    .map((m) => {
      // NOTE (Slice 19 Task 19 live-verify fix): `m.tools` is a list of
      // PACK/tool-name strings (validated against the palette by
      // validateIR, mirroring agent-builder's `suggestedServers`) — it is
      // NOT a `ToolSet`. `CrewMember.tools` (crew/types.ts), by contrast,
      // expects a real map of AI-SDK Tool objects, and `buildCrewAgent`
      // assigns it straight to the agent's `tools`. There is no live step
      // that resolves pack names into a member-scoped ToolSet yet, so
      // emitting `tools: [...]` here previously corrupted the member's
      // tool-calling (a string array spread as `{0: "brave-search"}`),
      // causing the agent to exhaust its step ceiling. Until member-scoped
      // MCP mounting exists, every member falls back to the crew-level
      // `tools` merged in `crewAgentMap` — so we deliberately drop the
      // per-member `tools` field rather than emit it broken.
      const ref = m.agentRef ? `,\n      agentRef: ${j(m.agentRef)}` : '';
      return `    {\n      name: ${j(m.name)},\n      role: ${j(m.role)},\n      goal: ${j(m.goal)},\n      backstory: ${j(m.backstory)},\n      requires: [Capability.Tools],\n      prefer: PreferPolicy.LargestThatFits${ref},\n    }`;
    })
    .join(',\n');
  const tasks = ir.tasks
    .map((t) => {
      const dep = t.dependsOn ? `,\n      dependsOn: ${j(t.dependsOn)}` : '';
      const verify = t.verify ? '\n      verify: true,' : '';
      return `    {\n      id: ${j(t.id)},\n      description: ${j(t.description)},\n      expectedOutput: ${j(t.expectedOutput)},\n      member: ${j(t.member)}${dep},\n      output: z.string(),${verify}\n    }`;
    })
    .join(',\n');
  // NOTE (Slice 19 Task 9 deviation from the brief): ir.process is a CrewProcess
  // ENUM value (Task 1's ir.ts uses z.nativeEnum(CrewProcess)), not a string
  // literal. Comparing it to the string literal 'hierarchical' as the brief's
  // draft did fails typecheck ("no overlap" comparing an enum to a string
  // literal type). Compare against the enum member instead.
  const proc =
    ir.process === CrewProcess.Hierarchical
      ? 'CrewProcess.Hierarchical'
      : 'CrewProcess.Sequential';
  return `import { z } from 'zod';
import { Capability, PreferPolicy } from '../src/core/types.ts';
import { defineCrew } from '../src/crew/define.ts';
import { CrewProcess } from '../src/crew/types.ts';

// Generated by the crew/workflow-builder (Slice 19). Safe to edit by hand.
export default defineCrew({
  id: ${j(ir.id)},${ir.description ? `\n  description: ${j(ir.description)},` : ''}
  process: ${proc},
  members: [
${members},
  ],
  tasks: [
${tasks},
  ],
});
`;
}

/** Render an IR to the TS source of a generated `crews/`/`workflows/` module.
 *  Deterministic — no model involved. Every string value is JSON.stringify'd
 *  (never raw-interpolated), so IR content can't break out of the generated
 *  source. Callers write the result under `crews/<id>.ts` or
 *  `workflows/<id>.ts` (repo root), which is why the relative imports above
 *  are `../src/...`. */
export function transpile(ir: CrewIR | WorkflowIR, shape: Shape): string {
  return shape === 'crew'
    ? transpileCrew(ir as CrewIR)
    : transpileWorkflow(ir as WorkflowIR);
}
